[project]
init_script="init.sh"
script_folder="script"
sh_script="run.sh"
py_script="run.py"
output_folder="output"
log_folder="logs"
virtual_env_path="./.venv"

[lambda]
lambda_script_folder="lambda"
lambda_sh_script="lambda_creation.sh"
lambda_py_script="local_lambda_function.py"
lambda_virtual_env_path="./lambda/.venv"

[mysql]
port=3306
database="superstore"

[api]
url="https://virtserver.swaggerhub.com/wcd_de_lab/top10/1.0.0/add"

[aws]
bucket_name='wcd-week3-lambda-miniproject'
region='us-east-2'
file_name='top_10_customers_20250130-203311.json'