[project]
init_script="init.sh"
script_folder="script"
sh_script="run.sh"
py_script="run.py"
output_folder="output"
log_folder="logs"
virtual_env_path="./.venv"

[mysql]
port=3306
database="superstore"

[api]
name="muse"
pagination_param="page"
page_number=50
url="https://www.themuse.com/api/public/jobs"

[aws]
bucket_name='wcd-projects-jobs-data-2024'
region='us-east-2'
file_name='jobs_20241126-173725.parquet'